name: 'chatx'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=chatxdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fUck_U_n1ggErs_@ss
      - MAX_LOGIN_ATTEMPTS=0
    networks:
      network:
        ipv4_address: 22.98.1.4

volumes:
  postgres-data:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 22.98.0.0/16
          gateway: 22.98.0.1